In [4]:
import numpy as np
import pandas as pd
student = {
    "Name" : ["Ali","Ahmad","Azeem","Ayesha","Amna"],
    "Computer" : [80,90,95,97,99],
    "English" : [60,70,80,90,80],
    "Maths" : [90,80,70,60,50]
}
#print(student)
df = pd.DataFrame(student)
df.to_csv("output.csv",index =False)

In [5]:
pd.read_csv("output.csv")

     Name  Computer  English  Maths
0     Ali        80       60     90
1   Ahmad        90       70     80
2   Azeem        95       80     70
3  Ayesha        97       90     60
4    Amna        99       80     50

In [6]:
df.head()

     Name  Computer  English  Maths
0     Ali        80       60     90
1   Ahmad        90       70     80
2   Azeem        95       80     70
3  Ayesha        97       90     60
4    Amna        99       80     50

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      str
 1   Computer  5 non-null      int64
 2   English   5 non-null      int64
 3   Maths     5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes

In [8]:
df.describe()

        Computer    English      Maths
count   5.000000   5.000000   5.000000
mean   92.200000  76.000000  70.000000
std     7.596052  11.401754  15.811388
min    80.000000  60.000000  50.000000
25%    90.000000  70.000000  60.000000
50%    95.000000  80.000000  70.000000
75%    97.000000  80.000000  80.000000
max    99.000000  90.000000  90.000000

In [10]:
df['Average'] = df.mean(axis=1,numeric_only=True)
print(df)

     Name  Computer  English  Maths    Average
0     Ali        80       60     90  76.666667
1   Ahmad        90       70     80  80.000000
2   Azeem        95       80     70  81.666667
3  Ayesha        97       90     60  82.333333
4    Amna        99       80     50  76.333333