# Agenda

1. Data Encoding

2. Features Scaling

# 1. Data Encoding

- Label Encoding
- One Hot Encoding

## Label Encoding

In [1]:
shirt_size = ['small', 'medium', 'large', 'medium', "small", "large", "small", "large", "medium"]
shirt_color = ["white", "black", "grey", "white", "black", "grey", "black", "black", "white"]

#price = [10, ]

# basket = ['apple', 'orange', 'grape', 'strawberry', 'melon', 'plum', 'banana', 'melon', 'plum', 'plum', 'grape', 'watermelon', 'melon', 'orange']

In [2]:

shirt_size = ['small', 'medium', 'large', 'medium', "small", "large", "small", "large", "medium"]

# Check if it is a nominal or ordinal (where order exist) feature? >> Ordinal 
# Which Encoding technique should be used? >> order exists, So applying >> Label Encoder

#  One-Hot Encoder (Where no order exist)

In [3]:
# Ecoding scheme
small = 1
medium = 2
large = 3

encoded_values = []

for i in shirt_size:
    print(f"Shirt Size: ", i)
    if i == 'small':
        encoded_values.append(small)
        print(f"Encoded Value: ", small)
    elif i == 'medium':
        encoded_values.append(medium)
        print(f"Encoded Value: ", medium)
    else:
        encoded_values.append(large)
        print(f"Encoded Value: ", large)

Shirt Size:  small
Encoded Value:  1
Shirt Size:  medium
Encoded Value:  2
Shirt Size:  large
Encoded Value:  3
Shirt Size:  medium
Encoded Value:  2
Shirt Size:  small
Encoded Value:  1
Shirt Size:  large
Encoded Value:  3
Shirt Size:  small
Encoded Value:  1
Shirt Size:  large
Encoded Value:  3
Shirt Size:  medium
Encoded Value:  2

In [4]:
print(shirt_size)

['small', 'medium', 'large', 'medium', 'small', 'large', 'small', 'large', 'medium']

In [5]:
print(encoded_values)

[1, 2, 3, 2, 1, 3, 1, 3, 2]

In [6]:
from sklearn.preprocessing import LabelEncoder # import encoder

encoder = LabelEncoder() # intialize encoder

labels = encoder.fit_transform(shirt_size)
print(labels)

[2 1 0 1 2 0 2 0 1]

In [7]:
encoder.classes_

array(['large', 'medium', 'small'], dtype='<U6')

In [8]:
for i in range(len(encoder.classes_)):
    print(f"{i} : {encoder.classes_[i]}")

0 : large
1 : medium
2 : small

In [9]:
# convert the numerical labels back to the original categorical
encoder.inverse_transform(labels)

array(['small', 'medium', 'large', 'medium', 'small', 'large', 'small',
       'large', 'medium'], dtype='<U6')

In [10]:
labels = encoder.fit_transform(labels).reshape(-1, 1)
labels

array([[2],
       [1],
       [0],
       [1],
       [2],
       [0],
       [2],
       [0],
       [1]])

**LabelEncoder does not support custom mappings directly** — it's designed to automatically assign integer labels in alphabetical order of the classes it sees.

However, you can simulate giving your own mapping in a few different ways depending on your needs:

In [11]:

shirt_size = ["L", "M", 'S', 'M', 'L', 'S', 'L', 'M']   #array
custom_mapping = {'S': 1, 'M': 2, 'L': 3}   #dictonary


import pandas as pd
encoded = pd.Series(shirt_size).map(custom_mapping)
print(encoded.tolist()) # Convert it to list

[3, 2, 1, 2, 3, 1, 3, 2]

In [12]:
shirt_size = ['small', 'medium', 'large', 'medium', "small", "large", "small", "large", "medium"]
custom_mapping = {'small': 0, 'medium': 1, 'large': 2}
encoded = pd.Series(shirt_size).map(custom_mapping)
print(encoded.tolist())

[0, 1, 2, 1, 0, 2, 0, 2, 1]

In [13]:
# Reverse Mapping
reverse_mapping = {v: k for k, v in custom_mapping.items()}
decoded = encoded.map(reverse_mapping)
print(decoded.tolist())

['small', 'medium', 'large', 'medium', 'small', 'large', 'small', 'large', 'medium']

## One Hot Encoding

OneHotEncoder will represent each color as a vector of binary values. 

`shirt_color = ["white", "black", "grey", "white", "black", "grey", "black", "black", "white"]`

Each color will be converted into a vector of 0s and 1s, with the 1 in the position of the color in the encoding.

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np

#basket = ['apple', 'orange', 'grape', 'strawberry', 'melon', 'plum', 'banana', 'melon', 'plum', 'plum', 'grape', 'watermelon', 'melon', 'orange']

shirt_color = ["white", "black", "grey", "white", "black", "grey", "black", "black", "white"] # 1d array

'''
OneHotEncoder expects a 2D array as input, where each row is a separate sample and each column represents a feature. 
Even if your data is a 1D array, like the shirt_color list, it needs to be reshaped to fit the expected input shape 
for scikit-learn's OneHotEncoder.
'''
shirt_color = np.array(shirt_color).reshape(-1, 1) # convert into 2d array 

# -1: Means "calculate the number of rows automatically"
# 1: Means "there should be 1 column".

onehot_encoder = OneHotEncoder()
onehot_labels = onehot_encoder.fit_transform(shirt_color).toarray()
onehot_labels

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [15]:
shirt_color

array([['white'],
       ['black'],
       ['grey'],
       ['white'],
       ['black'],
       ['grey'],
       ['black'],
       ['black'],
       ['white']], dtype='<U5')

In [16]:
onehot_labels

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [17]:
# Check the mappings
print("Categories (Mappings):", onehot_encoder.categories_)

Categories (Mappings): [array(['black', 'grey', 'white'], dtype='<U5')]

### Applying OneHot Encoder on dataframe

In [18]:
shirt_color = ["white", "black", "grey", "white", "black", "grey", "black", "black", "white"] # 1d array

df = pd.DataFrame({"shirt_color":shirt_color})

df

  shirt_color
0       white
1       black
2        grey
3       white
4       black
5        grey
6       black
7       black
8       white

In [19]:
onehot_encoder = OneHotEncoder()

# Reshape the data (because OneHotEncoder expects 2D input)
shirt_color_reshaped = df['shirt_color'].values.reshape(-1, 1)
onehot_labels = onehot_encoder.fit_transform(df['shirt_color'].values.reshape(-1, 1))

# Fit and transform the data
encoded_colors = onehot_encoder.fit_transform(shirt_color_reshaped)
encoded_colors.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [20]:
# Or do it as:
onehot_labels = onehot_encoder.fit_transform(df['shirt_color'].values.reshape(-1, 1))
onehot_labels.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [21]:
# Check the mappings
print("Categories (Mappings):", onehot_encoder.categories_)

Categories (Mappings): [array(['black', 'grey', 'white'], dtype=object)]

####  Using pandas.get_dummies()  `More Easier way of One-Hot Encoding`

- Pandas provides pd.get_dummies() function which takes a dataframe and returns a one-hot encoded dataframe right away.

In [22]:

shirt_color = ["white", "black", "grey", "white", "black", "grey", "black", "black", "white"]
import pandas as pd

df = pd.DataFrame(shirt_color, columns = ['Color'])
df

   Color
0  white
1  black
2   grey
3  white
4  black
5   grey
6  black
7  black
8  white

In [23]:
df_encoded = pd.get_dummies(df) # apply one-hot encoder
print(df_encoded)

   Color_black  Color_grey  Color_white
0        False       False         True
1         True       False        False
2        False        True        False
3        False       False         True
4         True       False        False
5        False        True        False
6         True       False        False
7         True       False        False
8        False       False         True

In [24]:
df_encoded = pd.get_dummies(df,  dtype=int) # apply one-hot encoder
print(df_encoded)

   Color_black  Color_grey  Color_white
0            0           0            1
1            1           0            0
2            0           1            0
3            0           0            1
4            1           0            0
5            0           1            0
6            1           0            0
7            1           0            0
8            0           0            1

# 2. Feature Scaling

In [25]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [26]:
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

## StandardScaler()

StandardScaler() in Scikit-Learn scales the values so that their mean is 0 and variance is 1 — Gaussian distribution. 

It is very important to convert dataset so that it follows the Gaussian distribution in some ML algorithms. 

For example, linear regression or logistic regression models assume that data follow the Gaussian distribution.

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
standard_iris = scaler.fit_transform(iris_df)
standard_iris = pd.DataFrame(standard_iris, columns = iris.feature_names)
standard_iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [28]:
standard_iris.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-4.736952e-16,-7.815970e-16,-4.263256e-16,-4.736952e-16
std,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00
min,-1.870024e+00,-2.433947e+00,-1.567576e+00,-1.447076e+00
25%,-9.006812e-01,-5.923730e-01,-1.226552e+00,-1.183812e+00
50%,-5.250608e-02,-1.319795e-01,3.364776e-01,1.325097e-01
75%,6.745011e-01,5.586108e-01,7.627583e-01,7.906707e-01
max,2.492019e+00,3.090775e+00,1.785832e+00,1.712096e+00

In [29]:
standard_iris.mean()

sepal length (cm)   -4.736952e-16
sepal width (cm)    -7.815970e-16
petal length (cm)   -4.263256e-16
petal width (cm)    -4.736952e-16
dtype: float64

In [30]:
standard_iris.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

##  MinMaxScaler()

converts data into some value in the range [0, 1], or else in the rnage [-1, 1] if there are negative values. 

With the iris data, since there are no negative values, the range of data should be between 0 and 1.

In [31]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
minmax_iris = minmax.fit_transform(iris_df)
minmax_iris = pd.DataFrame(minmax_iris, columns = iris.feature_names)
minmax_iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [32]:
minmax_iris.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,0.428704,0.440556,0.467458,0.458056
std,0.230018,0.181611,0.299203,0.317599
min,0.000000,0.000000,0.000000,0.000000
25%,0.222222,0.333333,0.101695,0.083333
50%,0.416667,0.416667,0.567797,0.500000
75%,0.583333,0.541667,0.694915,0.708333
max,1.000000,1.000000,1.000000,1.000000

In [33]:
minmax_iris.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [34]:
minmax_iris.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

### References

https://medium.com/@chyun55555/data-preprocessing-methods-with-scikit-learn-python-98437e8d93cb